# Control System Bootcamp - Video 5-6

In [4]:
from IPython.display import HTML
HTML("""
<iframe width="560" height="315" src="https://www.youtube.com/embed/FLByezr38Ps" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
""")

## Controllability, Reachability, and Eigenvalue Placement

<img src="./images/FeedbackSystem.png" alt="FeedbackSystem" style="display:block; float:none; margin-left:auto; margin-right:auto; width:30%">

### Controllabillity examples

**Note: \textcolor{green} did not work in JupyterLab, but in VS Code**

$$
\begin{align*} 
(*)\quad
&\begin{bmatrix} \dot x_1 \\ \dot x_2 \end{bmatrix} = 
\underbrace{\begin{bmatrix} 1 & 0 \\ 0 & 2 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} }_\text{unctrb $x$} +
\begin{bmatrix} 0 \\ 1 \end{bmatrix}u\quad
\underbrace{\begin{pmatrix} + \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} \begin{bmatrix} u_1 \\ u_2  \end{bmatrix}
\end{pmatrix}}_\text{ctrb $x$}
\\[11pt]
(**)\quad
&\begin{bmatrix} \dot x_1 \\ \dot x_2 \end{bmatrix} = 
\underbrace{\begin{bmatrix} 1 & \bf1 \\ 0 & 2 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} }_\text{ctrb $x$} +
\begin{bmatrix} 0 \\ 1 \end{bmatrix}u
\end{align*} 
$$

### Controllabillity matrix
$ C = \begin{bmatrix} A & AB & A^2B &... &A^{n-1}B\end{bmatrix} \iff rank(C) = n$, then system is controlable.

$$
\begin{align*} 
(*)\quad
& C = \begin{bmatrix} 0 & 1 \\ 0 & 2 \end{bmatrix} \quad rank=1, unctrb.
\\[11pt]
(**)\quad
& C = \begin{bmatrix} 0 & 1 \\ 1 & 2 \end{bmatrix} \quad rank=2, ctrb.
\end{align*} 
$$

- [Python Control Systems Library](https://web.math.princeton.edu/~cwrowley/python-control/index.html)
- [control.ctrb - Python Control Systems Library documentation](https://web.math.princeton.edu/~cwrowley/python-control/generated/control.ctrb.html)

In [2]:
import numpy as np
import control as ct

A1, B1 = np.array([[1, 0], [0, 2]]), np.array([[0], [1]])
A2, B2 = np.array([[1, 1], [0, 2]]), np.array([[0], [1]])
A1, B1, A2, B2

(array([[1, 0],
        [0, 2]]),
 array([[0],
        [1]]),
 array([[1, 1],
        [0, 2]]),
 array([[0],
        [1]]))

In [3]:
C1, C2 = ct.ctrb(A1, B1), ct.ctrb(A2, B2)
C1, np.linalg.matrix_rank(C1), C2, np.linalg.matrix_rank(C2)

(array([[0., 0.],
        [1., 2.]]),
 1,
 array([[0., 1.],
        [1., 2.]]),
 2)

Video 6: Controllability, Reachability, and Eigenvalue Placement

### Equivalences of Controllability

### 1. System is controllable


### 2. Arbitrary eigenvalue (pole) placement
$$U = -Kx$$
which means $\dot x = (A - Bk)x$. $(A - Bk)$ is arbitrary eigenvalues.

### 3. Arbitrary eigenvalue (pole) placement
$$U = -Kx$$
which means $\dot x = (A - Bk)x$. $(A - Bk)$ is arbitrary eigenvalues.

##### Commands
| Matlab | [Python](https://python-control.readthedocs.io/en/latest/generated/control.matlab.place.html) |
| :----: | :----: |
|`K = place(A, B, eigs)`| `control.matlab.place(A, B, p)` |